//go:build !ignore_autogenerated

/*
Copyright 2023 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Goal) DeepCopyInto(out *Goal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Goal.
func (in *Goal) DeepCopy() *Goal {
	if in == nil {
		return nil
	}
	out := new(Goal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Goal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalList) DeepCopyInto(out *GoalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Goal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalList.
func (in *GoalList) DeepCopy() *GoalList {
	if in == nil {
		return nil
	}
	out := new(GoalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GoalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalObservation) DeepCopyInto(out *GoalObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalObservation.
func (in *GoalObservation) DeepCopy() *GoalObservation {
	if in == nil {
		return nil
	}
	out := new(GoalObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalParameters) DeepCopyInto(out *GoalParameters) {
	*out = *in
	if in.SiteDomain != nil {
		in, out := &in.SiteDomain, &out.SiteDomain
		*out = new(string)
		**out = **in
	}
	if in.SiteDomainRef != nil {
		in, out := &in.SiteDomainRef, &out.SiteDomainRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SiteDomainSelector != nil {
		in, out := &in.SiteDomainSelector, &out.SiteDomainSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EventName != nil {
		in, out := &in.EventName, &out.EventName
		*out = new(string)
		**out = **in
	}
	if in.PagePath != nil {
		in, out := &in.PagePath, &out.PagePath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalParameters.
func (in *GoalParameters) DeepCopy() *GoalParameters {
	if in == nil {
		return nil
	}
	out := new(GoalParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalSpec) DeepCopyInto(out *GoalSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalSpec.
func (in *GoalSpec) DeepCopy() *GoalSpec {
	if in == nil {
		return nil
	}
	out := new(GoalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalStatus) DeepCopyInto(out *GoalStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalStatus.
func (in *GoalStatus) DeepCopy() *GoalStatus {
	if in == nil {
		return nil
	}
	out := new(GoalStatus)
	in.DeepCopyInto(out)
	return out
}
