//go:build !ignore_autogenerated

/*
Copyright 2023 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Guest) DeepCopyInto(out *Guest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Guest.
func (in *Guest) DeepCopy() *Guest {
	if in == nil {
		return nil
	}
	out := new(Guest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Guest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestList) DeepCopyInto(out *GuestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Guest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestList.
func (in *GuestList) DeepCopy() *GuestList {
	if in == nil {
		return nil
	}
	out := new(GuestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestObservation) DeepCopyInto(out *GuestObservation) {
	*out = *in
	if in.InvitedAt != nil {
		in, out := &in.InvitedAt, &out.InvitedAt
		*out = (*in).DeepCopy()
	}
	if in.AcceptedAt != nil {
		in, out := &in.AcceptedAt, &out.AcceptedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestObservation.
func (in *GuestObservation) DeepCopy() *GuestObservation {
	if in == nil {
		return nil
	}
	out := new(GuestObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestParameters) DeepCopyInto(out *GuestParameters) {
	*out = *in
	if in.SiteDomain != nil {
		in, out := &in.SiteDomain, &out.SiteDomain
		*out = new(string)
		**out = **in
	}
	if in.SiteDomainRef != nil {
		in, out := &in.SiteDomainRef, &out.SiteDomainRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SiteDomainSelector != nil {
		in, out := &in.SiteDomainSelector, &out.SiteDomainSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestParameters.
func (in *GuestParameters) DeepCopy() *GuestParameters {
	if in == nil {
		return nil
	}
	out := new(GuestParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestSpec) DeepCopyInto(out *GuestSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestSpec.
func (in *GuestSpec) DeepCopy() *GuestSpec {
	if in == nil {
		return nil
	}
	out := new(GuestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestStatus) DeepCopyInto(out *GuestStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestStatus.
func (in *GuestStatus) DeepCopy() *GuestStatus {
	if in == nil {
		return nil
	}
	out := new(GuestStatus)
	in.DeepCopyInto(out)
	return out
}
