apiVersion: plausible.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  namespace: default
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: plausible-credentials
      namespace: crossplane-system
      key: credentials
  # baseURL: "https://plausible.yourdomain.com"  # Optional: defaults to plausible.io