apiVersion: goal.plausible.m.crossplane.io/v1beta1
kind: Goal
metadata:
  namespace: default
  name: example-event-goal
spec:
  forProvider:
    # Reference the site by name
    siteDomainRef:
      name: example-site
    goalType: event
    eventName: "Signup"
  providerConfigRef:
    name: default