apiVersion: goal.plausible.m.crossplane.io/v1beta1
kind: Goal
metadata:
  namespace: default
  name: example-page-goal
spec:
  forProvider:
    # Directly specify the site domain
    siteDomain: "example.com"
    goalType: page
    pagePath: "/thank-you"
  providerConfigRef:
    name: default